### ISSUE TITLE
Entity Equipment

### ISSUE THREAD

**Issue by Khrystia-Sliusarchuk** [Paliy2/Project-alias#1]
### Description

Entity `Equipment` has to be created with the following properties:

- [x] `number : String` - to record a unique auto-generated equipment number; `KEY`. 
- [x] `title : String` -- to record an equipment title. (No whitespaces)
- [x] `equipmentType : Equipment Type` -- to record an equipment type this equipment belongs to. (Autocompleted, required)
- [x] `vehicle : Vehicle` -- to record a vehicle this equipment belongs to. (Autocompleted)

It is also necessary to create `Equipment Centre` to search and review the existing equipment and `Equipment Master` to create the new and edit the existing equipment.

### Expected outcome

`Equipment` record is created and associated with the relevant `Equipment Type`.

**Comment by 01es** [comment]
Can an equipment be reallocated from one vehicle to another? If yes, then the proposed approach by using property `assignedVehicle` would not be sufficient. A one-2-many association would be required to track the movement of an equipment between different vehicles.

**Comment by 01es** [comment]
If `EquipmentType` is a subdivision of `EquipmentClass`, why do you need to have both properties `equipmentClass` and `equipmentType`?

**Comment by 01es** [comment]
@Nazar4ick and @Khrystia-Sliusarchuk, properties `equipmentType` and `assignedVehicle` are marked as "autogenerated". What is the meaning of this?

Also, consider if equipment may get moved off/on or between vehicles. This is the same question as before https://github.com/Paliy2/Project-alias/issues/1#issuecomment-986470198.

**Comment by Khrystia-Sliusarchuk** [comment]
> @Nazar4ick and @Khrystia-Sliusarchuk, properties `equipmentType` and `assignedVehicle` are marked as "autogenerated". What is the meaning of this?
> 
> Also, consider if equipment may get moved off/on or between vehicles. This is the same question as before [#1 (comment)](https://github.com/Paliy2/Project-alias/issues/1#issuecomment-986470198).

We meant "autocompleted", not "autogenerated". That was a typo.

Regarding the ability to move equipment from off/on or between vehicles, our team decided that tracking this movement is not a necessary part of MVP.
