### ISSUE TITLE
Entity Form Type

### ISSUE THREAD

**Issue by Khrystia-Sliusarchuk** [Paliy2/Project-alias#12]
### Description
Form type is used to make different templates for forms. This is needed for daily check-ups, as the same form is used every day for the specified role. These templates are different for different roles.

Entity `Form Type` has to be created with the following properties:

- [x] `title : String` -- to record a unique form type title; `KEY`. (No whitespaces)
- [x] `desc : String` -- to record a form type description.
- [x] `assignedRole: Role` -- to record a role this form type belongs to. (Autogenerated, required)
- [x] `formClass: FormClass` -- to keep track of the classes we need to update with the BatchUpdate action.
- [ ] `formTypeItems : array of Form Type Items` -- to keep track of form items necessary for checking in this specific form type. (required)

It is also necessary to create `Form Type Centre` to search and review the existing form types and `Form Type Master` to create the new and edit the existing form types.

### Expected outcome

Ability to perform classification of forms by types.

**Comment by Paliy2** [comment]
How to add formTypeItems to the UI?

**Comment by Paliy2** [comment]
Exception in thread "main" java.lang.IllegalStateException: ua.com.fielden.platform.domaintree.exceptions.DomainTreeException: Could not [un]check 'disabled' property [formTypeItems] in type [FormType$$TgEntity_c6e8252c5be040a5b3a44390f5ad0f53].


![image](https://user-images.githubusercontent.com/52251850/147836639-5e3cef9a-88e5-42b9-81f9-d26aa5996eda.png)
