### ISSUE TITLE
Entity Form

### ISSUE THREAD

**Issue by saniochky** [Paliy2/Project-alias#16]
### Description

Entity Form has to be created and have the following properties:

- [ ] `formItems: array of Form Items` -- to keep track of form items necessary for checking
- [x] `person : Person` -- to record the Form owner; `Composite Key`. (Autogenerated)
- [x] `date: Date` -- to record the date Form was created; `Composite Key`. (in format dd.mm.yyyy)
- [x] `status: String` -- to record the status of the Form. (Autogenerated, required)

It is also necessary to create `Form Centre` to search and review the existing forms and `Form Master` to create new and edit existing forms.

### Expected outcome

Entity Form can be created with the necessary fields.

**Comment by Paliy2** [comment]
How to add formTypeItems to the UI?
