### ISSUE TITLE
Entity Person Role

### ISSUE THREAD

**Issue by Khrystia-Sliusarchuk** [Paliy2/Project-alias#17]
### Description
This entity is needed to track which roles were assigned to a person, as an employee can have different roles every day.

Entity `Person Role` has to be created with the following properties:

- [x] `person : Person` -- to record the person to whom this role was assigned to; `Composite Key`.
- [x] `assignedRole : Role` -- to record the role that was assigned to this person. (Autogenerated, required)
- [x] `assignDate : Date` -- to record the date when the role was assigned to this person; `Composite Key`. (in format dd.mm.yyyy)

### Expected outcome
Ability to track the role of the person at a specific time period.

**Comment by saniochky** [comment]
I made two pushes for this issue but forgot to add "#17" at the start of the comment so it is not visible here. But the issue itself is complete

**Comment by saniochky** [comment]
Issue is done
