### ISSUE TITLE
Entity Form Type Item

### ISSUE THREAD

**Issue by Khrystia-Sliusarchuk** [Paliy2/Project-alias#18]
### Description
This entity is used in form templates.

Entity `Form Type Item` has to be created with the following properties:

- [x] `title : String` -- to record a unique form type item title; `KEY`. (No whitespaces)
- [x] `desc : String` -- to record a form type item description.

It is also necessary to create `Form Type Item Centre` to search and review the existing form type items and `Form Type Item Master` to create new and edit the existing form type items.

### Expected outcome
Ability to create form type items for using in templates .

**Comment by saniochky** [comment]
Issue is closed
