### ISSUE TITLE
Entity Form Item

### ISSUE THREAD

**Issue by Khrystia-Sliusarchuk** [Paliy2/Project-alias#19]
### Description
This entity is used in forms.

Entity `Form Item` has to be created with the following properties:

- [x] `formTypeItem : Form Type Item` -- to record from which form type item this form item is created. (Autocompleted, required)
- [x] `accepted: Boolean` -- to record acceptance status of this form item

It is also necessary to create `Form Item Centre` to search and review the existing form items and `Form Item Master` to create new and edit the existing form items.

### Expected outcome
Ability to create form items to use in forms.

**Comment by Paliy2** [comment]
Need to Improve UI

**Comment by Paliy2** [comment]
Finished
