### ISSUE TITLE
Entity Vehicle

### ISSUE THREAD

**Issue by Nazar4ick** [Paliy2/Project-alias#4]
### Description

Entity Vehicle has to be created and have the following properties:

- [x] `model : String` -- to record the model of the vehicle (required). 
- [x] `number : String` -- to record the number of the vehicle (e.g. AA9999AA) (required); `KEY`.
- [x] `vehicleType : VehicleType` -- to record to which vehicle type does this vehicle belong to (required, autocompleted).
- [x] `active : bool` -- to record whether a vehicle is active or not at the moment (required).
- [x] `assignedDriver : Person` -- to record which driver is currently assigned to the vehicle (optional).
- [x] `description : String` -- to record some additional information about the vehicle (optional).

It is also necessary to create `Vehicle Centre` to search and review the existing equipment and `Vehicle Master` to create new and edit existing vehicles.

### Expected outcome

Ability to create vehicles with necessary fields.

**Comment by 01es** [comment]
It is often the case that rego (registration number) and an asset (vehicle) number in the system are two different things. The reason for this is that it is necessary to provide a unique identifier for a vehicle record (in terms of the business key), while being able to reuse rego for some other vehicle. This happens, for example, when a vehicle gets decommissioned, but the rego number plate is reused by another vehicle.

Do you recall the concept of activatable entities?

**Comment by 01es** [comment]
@Nazar4ick, properties have inconsistent specs -- the first part is the name, the second part is the type. Types and property names should be camel case, but properties start with a small letter and types start with a capital letter.

So, instead of `Model: String` it should be `model: String` (or even `model: Model`, were `Model` is another concept).
And `Person : assignedDriver` should really be `assignedDriver: Person`.

**Comment by 01es** [comment]
> It is often the case that rego (registration number) and an asset (vehicle) number in the system are two different things. The reason for this is that it is necessary to provide a unique identifier for a vehicle record (in terms of the business key), while being able to reuse rego for some other vehicle. This happens, for example, when a vehicle gets decommissioned, but the rego number plate is reused by another vehicle.
> 
> Do you recall the concept of activatable entities?

@Nazar4ick and @Khrystia-Sliusarchuk, did you consider this comment?

**Comment by Nazar4ick** [comment]
> @Nazar4ick, properties have inconsistent specs -- the first part is the name, the second part is the type. Types and property names should be camel case, but properties start with a small letter and types start with a capital letter.
> 
> So, instead of `Model: String` it should be `model: String` (or even `model: Model`, were `Model` is another concept). And `Person : assignedDriver` should really be `assignedDriver: Person`.

Resolved the inconsistency

**Comment by Nazar4ick** [comment]
> > It is often the case that rego (registration number) and an asset (vehicle) number in the system are two different things. The reason for this is that it is necessary to provide a unique identifier for a vehicle record (in terms of the business key), while being able to reuse rego for some other vehicle. This happens, for example, when a vehicle gets decommissioned, but the rego number plate is reused by another vehicle.
> > Do you recall the concept of activatable entities?
> 
> @Nazar4ick and @Khrystia-Sliusarchuk, did you consider this comment?

From our conversations with the fire department we came to the conclusion that such situations are edge cases, so we decided not to consider this in our MVP.
