### ISSUE TITLE
Entity Form Item Found No Matching value

### ISSUE THREAD

**Issue by Paliy2** [Paliy2/Project-alias#43]
Despite I have created several FormTypeItems, the lookup field does not see them. 
I can create new FormTypeItems from the FormItem center

![image](https://user-images.githubusercontent.com/52251850/147835878-87e3c50b-9c31-4cc4-a407-a1d15010376a.png)

**Comment by homedirectory** [comment]
This is due to the fact that there are no **active** instances of `FormTypeItem`. Autocompletion finds only active ones. Modify your implementation of `FormTypeItemDao` so that it automatically sets saved instances to be active.

**Comment by Paliy2** [comment]
The concept is clear. The Dao files have been fixed.
