### ISSUE TITLE
Change user password on request 

### ISSUE THREAD

**Issue by Paliy2** [Paliy2/Project-alias#5]
### Description
`Department Captain` can change the password on the user request. 

### Expected outcome
- [ ] The form should have the following fields: `New password` and `Date` (autocomplete)

- [ ] The password can be changed only by the Department Captain role.

**Comment by 01es** [comment]
This functionality would weaken the systems security. Users should be able to reset their own passwords. Such functionality is already provided as part of the core TG functionality for you. Does this really deserve a separate issue?
